const fs = require("fs/promises");
const path = require("path");
const crypto = require("crypto");
const DATA_FILE = path.join(__dirname, "splitwise-house-data.json"), KV_KEY = "splitwise-house:state:v1";
const defaultState = { members:["Chan","Mika","Jules","Rina","Paolo","Kai"].map((name,index)=>({id:`member-${index+1}`,name})), funds:[{id:"fund-market",title:"Wet market run",description:"Vegetables, fish, rice, and household basics",date:"2026-08-29",total:1845,memberIds:["member-1","member-2","member-3","member-4","member-5","member-6"],payments:{"member-1":true,"member-2":true,"member-3":true},icon:"◈",updatedAt:"2026-08-29T10:00:00.000Z"},{id:"fund-car",title:"Car rental & gas",description:"Saturday trip to the wet market",date:"2026-08-29",total:1260,memberIds:["member-1","member-2","member-3","member-4","member-5","member-6"],payments:{"member-1":true,"member-4":true},icon:"◌",updatedAt:"2026-08-29T11:00:00.000Z"},{id:"fund-internet",title:"August internet",description:"Monthly house Wi-Fi",date:"2026-08-01",total:1599,memberIds:["member-1","member-2","member-3","member-4","member-5","member-6"],payments:{"member-1":true,"member-2":true,"member-3":true,"member-4":true,"member-5":true,"member-6":true},icon:"◫",updatedAt:"2026-08-01T08:00:00.000Z"}] };
defaultState.members = ["Chan","Winston","Wei","Ann","Lianne"].map((name,index)=>({id:`member-${index+1}`,name}));
defaultState.funds.forEach(fund => { fund.memberIds = ["member-1","member-2","member-3","member-4","member-5"]; delete fund.payments["member-6"]; });
const cloneDefault = () => JSON.parse(JSON.stringify(defaultState));
const hasKv = () => Boolean(process.env.KV_REST_API_URL && process.env.KV_REST_API_TOKEN);
async function readState(){if(hasKv()){const response=await fetch(`${process.env.KV_REST_API_URL}/get/${encodeURIComponent(KV_KEY)}`,{headers:{Authorization:`Bearer ${process.env.KV_REST_API_TOKEN}`}});if(!response.ok)throw new Error("Could not read the configured Vercel KV database.");const payload=await response.json();return payload.result?JSON.parse(payload.result):cloneDefault();}try{return JSON.parse(await fs.readFile(DATA_FILE,"utf8"));}catch(error){if(error.code==="ENOENT")return cloneDefault();throw error;}}
async function writeState(state){if(hasKv()){const response=await fetch(process.env.KV_REST_API_URL,{method:"POST",headers:{Authorization:`Bearer ${process.env.KV_REST_API_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify(["SET",KV_KEY,JSON.stringify(state)])});if(!response.ok)throw new Error("Could not save to the configured Vercel KV database.");return state;}await fs.writeFile(DATA_FILE,JSON.stringify(state,null,2),"utf8");return state;}
function sendJson(response,status,body){response.statusCode=status;response.setHeader("Content-Type","application/json; charset=utf-8");response.setHeader("Cache-Control","no-store");response.end(JSON.stringify(body));}
function body(request){return new Promise((resolve,reject)=>{let text="";request.on("data",chunk=>{text+=chunk;if(Buffer.byteLength(text)>1000000){reject(new Error("Request is too large."));request.destroy();}});request.on("end",()=>{try{resolve(text?JSON.parse(text):{});}catch{reject(new Error("Request body must be valid JSON."));}});request.on("error",reject);});}
function validFund(input,members){const title=String(input.title||"").trim(),description=String(input.description||"").trim(),date=String(input.date||""),total=Number(input.total),receipt=input.receipt==null?null:String(input.receipt);const ids=[...new Set(Array.isArray(input.memberIds)?input.memberIds.filter(id=>typeof id==="string"):[])].filter(id=>members.some(member=>member.id===id));if(!title)throw new Error("A fund title is required.");if(title.length>80||description.length>160)throw new Error("Please shorten the title or description.");if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error("Choose a valid date.");if(!Number.isFinite(total)||total<=0)throw new Error("Enter a total greater than zero.");if(!ids.length)throw new Error("Select at least one current member.");if(receipt&&(!/^data:image\/(png|jpeg|webp);base64,/i.test(receipt)||receipt.length>900000))throw new Error("Choose a smaller PNG, JPEG, or WebP receipt image.");return {title,description,date,total:Math.round(total*100)/100,memberIds:ids,receipt};}
async function handler(request,response){const url=new URL(request.url,"http://localhost"),parts=url.pathname.split("/").filter(Boolean);if(url.pathname==="/api/health")return sendJson(response,200,{ok:true,storage:hasKv()?"vercel-kv":"local-file"});if(url.pathname==="/api/state"&&request.method==="GET")return sendJson(response,200,await readState());const state=await readState();if(url.pathname==="/api/members"&&request.method==="POST"){const input=await body(request),name=String(input.name||"").trim();if(!name||name.length>50)throw new Error("Enter a member name up to 50 characters.");if(state.members.some(member=>member.name.toLowerCase()===name.toLowerCase()))throw new Error("That member is already in this group.");state.members.push({id:crypto.randomUUID(),name});return sendJson(response,201,await writeState(state));}if(parts[0]==="api"&&parts[1]==="members"&&parts[2]&&request.method==="DELETE"){const id=parts[2];if(!state.members.some(member=>member.id===id))return sendJson(response,404,{error:"Member not found."});state.members=state.members.filter(member=>member.id!==id);return sendJson(response,200,await writeState(state));}if(url.pathname==="/api/funds"&&request.method==="POST"){const input=validFund(await body(request),state.members);state.funds.push({id:crypto.randomUUID(),...input,payments:{},icon:"◈",updatedAt:new Date().toISOString()});return sendJson(response,201,await writeState(state));}if(parts[0]==="api"&&parts[1]==="funds"&&parts[2]){const fund=state.funds.find(item=>item.id===parts[2]);if(!fund)return sendJson(response,404,{error:"Split fund not found."});if(request.method==="DELETE"&&parts.length===3){state.funds=state.funds.filter(item=>item.id!==fund.id);return sendJson(response,200,await writeState(state));}if(request.method==="PATCH"&&parts.length===3){const update=validFund(await body(request),state.members),payments={};update.memberIds.forEach(id=>{if(fund.payments?.[id])payments[id]=true;});Object.assign(fund,update,{payments,updatedAt:new Date().toISOString()});return sendJson(response,200,await writeState(state));}if(request.method==="PATCH"&&parts[3]==="payments"){const input=await body(request);if(!fund.memberIds.includes(input.memberId))throw new Error("That member is not part of this fund.");fund.payments||={};if(input.paid)fund.payments[input.memberId]=true;else delete fund.payments[input.memberId];fund.updatedAt=new Date().toISOString();return sendJson(response,200,await writeState(state));}}return sendJson(response,404,{error:"API endpoint not found."});}
module.exports=async(request,response)=>{try{await handler(request,response);}catch(error){sendJson(response,400,{error:error.message||"Something went wrong."});}};

const originalApiHandler = module.exports;
module.exports = async (request, response) => {
  const url = new URL(request.url, "http://localhost");
  const parts = url.pathname.split("/").filter(Boolean);
  const isMembersRoute = parts[0] === "api" && parts[1] === "members";
  const isSingleMember = isMembersRoute && parts[2] && parts.length === 3;
  const supportsMemberDetails = (url.pathname === "/api/members" && request.method === "POST") || (isSingleMember && request.method === "PATCH");
  if (!supportsMemberDetails) return originalApiHandler(request, response);
  try {
    const input = await body(request), name = String(input.name || "").trim(), contact = String(input.contact || "").trim(), nickname = String(input.nickname || "").trim(), label = String(input.label || "").trim(), avatar = input.avatar == null ? "" : String(input.avatar), paymentMethods = Array.isArray(input.paymentMethods) ? input.paymentMethods.slice(0, 3).map(item => ({ id:String(item.id || crypto.randomUUID()), label:String(item.label || "").trim(), image:String(item.image || "") })) : [];
    if (!name || name.length > 50) throw new Error("Enter a member name up to 50 characters.");
    if (contact.length > 80 || nickname.length > 30 || label.length > 40) throw new Error("Keep account details within the allowed length.");
    if (avatar && (!/^data:image\/(png|jpeg|webp);base64,/i.test(avatar) || avatar.length > 180000)) throw new Error("Choose a smaller profile photo.");
    if (paymentMethods.some(method => !method.label || method.label.length > 30 || !/^data:image\/(png|jpeg|webp);base64,/i.test(method.image) || method.image.length > 180000)) throw new Error("Each payment QR needs a bank label and a smaller PNG, JPEG, or WebP image.");
    const state = await readState();
    const member = isSingleMember ? state.members.find(item => item.id === parts[2]) : null;
    if (isSingleMember && !member) return sendJson(response, 404, { error:"Member not found." });
    if (state.members.some(item => item.id !== member?.id && item.name.toLowerCase() === name.toLowerCase())) throw new Error("That member is already in this group.");
    if (member) Object.assign(member, { name, contact, nickname, label, avatar, paymentMethods });
    else state.members.push({ id:crypto.randomUUID(), name, contact, nickname, label, avatar, paymentMethods });
    return sendJson(response, member ? 200 : 201, await writeState(state));
  } catch (error) { return sendJson(response, 400, { error:error.message || "Something went wrong." }); }
};

function validFund(input, members) {
  const title = String(input.title || "").trim(), description = String(input.description || "").trim().replace(/<(?!\/?(?:b|strong|i|em|ul|ol|li|p|br)\b)[^>]*>/gi, "").replace(/<(b|strong|i|em|ul|ol|li|p|br)(?:\s[^>]*)?>/gi, "<$1>").replace(/<\/(b|strong|i|em|ul|ol|li|p)>/gi, "</$1>"), date = String(input.date || ""), total = Number(input.total), receipt = input.receipt == null ? null : String(input.receipt);
  const ids = [...new Set(Array.isArray(input.memberIds) ? input.memberIds.filter(id => typeof id === "string") : [])].filter(id => members.some(member => member.id === id));
  if (!title) throw new Error("A fund title is required.");
  if (title.length > 80 || description.length > 1200) throw new Error("Please shorten the title or description.");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error("Choose a valid date.");
  if (!Number.isFinite(total) || total <= 0) throw new Error("Enter a total greater than zero.");
  if (!ids.length) throw new Error("Select at least one current member.");
  if (receipt && (!/^data:image\/(png|jpeg|webp);base64,/i.test(receipt) || receipt.length > 900000)) throw new Error("Choose a smaller PNG, JPEG, or WebP receipt image.");
  return { title, description, date, total:Math.round(total * 100) / 100, memberIds:ids, receipt };
}
